--creating table currency_dbt
CREATE TABLE CURRENCY_EXCHANGE_RATE_DBT
(
    ID LONG AUTO_INCREMENT,
    CURRENCY VARCHAR NOT NULL,
    CURRENCY_BASE VARCHAR NOT NULL,
    BUY VARCHAR NOT NULL,
    SELL VARCHAR NOT NULL,
    EXCHANGE_DATE DATE,
    EXCHANGE_TIME TIME
);

CREATE UNIQUE INDEX CURRENCY_DBT_ID_UINDEX
	ON CURRENCY_EXCHANGE_RATE_DBT (ID);

ALTER TABLE CURRENCY_EXCHANGE_RATE_DBT
    ADD CONSTRAINT CURRENCY_DBT_PK
        PRIMARY KEY (ID);


CREATE TABLE CURRENCY_ORDER_DBT
(
    ID LONG AUTO_INCREMENT,
    CURRENCY_BUY VARCHAR NOT NULL,
    CURRENCY_SELL VARCHAR NOT NULL,
    SUM_SELL NUMERIC NOT NULL,
    SUM_BUY NUMERIC NOT NULL,
    CLIENT_NAME VARCHAR NOT NULL,
    PHONE VARCHAR NOT NULL,
    ORDER_STATUS VARCHAR NOT NULL,
    OTP_PASSWORD VARCHAR NOT NULL,
    ORDER_DATE date,
    ORDER_TIME time
);

create unique index CURRENCY_ORDER_DBT_ID_UINDEX
    on CURRENCY_ORDER_DBT (ID);

alter table CURRENCY_ORDER_DBT
    add constraint CURRENCY_ORDER_DBT_PK
        primary key (ID);

/*INSERT INTO CURRENCY_ORDER_DBT(ID, CURRENCY_BUY, CURRENCY_SELL, SUM_SALE, SUM_BUY, CLIENT_NAME, PHONE, ORDER_STATUS, OTP_PASSWORD)
VALUES (1, 'USD', 'UAH', 25, 0, 'TEST USER', '095-1234567', 0, '0123');*/

CREATE SEQUENCE HIBERNATE_SEQUENCE
/*    START WITH 1*/
    MAXVALUE 99999999999
    MINVALUE 1
    NOCYCLE
    CACHE 20;